### ISSUE TITLE
Revisit using scikit-learn for dictionary learning as an alternative to SPAMS

### ISSUE THREAD

**Issue by jakirkham** [nanshe-org/nanshe#296]
It has been a year and a half since the last release of SPAMS ( see news http://spams-devel.gforge.inria.fr/index.html ). Additionally, we are running into problems getting it to build with the recent NumPy 1.10.0 release ( https://github.com/nanshe-org/nanshe-build/issues/8 ). It would be nice to have a more regularly maintained and commonly used library as a dependency here. It appears that the implementation detail isn't so different from that in scikit-learn according to one of the maintainers ( https://github.com/scikit-learn/scikit-learn/issues/4069#issuecomment-69449604 ). As dictionary learning is somewhat decoupled from the implementation, this may be doable. At a minimum, the goal here would be to make SPAMS an optional (soft) dependency.

**Comment by fdiego** [comment]
I remember that the main issue was the speed-up, but go ahead if there are compatibility problems.

**Comment by jakirkham** [comment]
Yes, but we have changed some things since then. When we used SPAMS before it ran with OpenMP threading, but we no longer do this as parallelism now occurs by breaking up data at the beginning of our algorithm and passing it through. Thus, SPAMS runs in a singled threaded mode; so, there is no benefit from this OpenMP parallelism. It would be worth reassessing how much slower it is.

Based on what is stated here ( https://github.com/scikit-learn/scikit-learn/issues/4069#issuecomment-69449604 ), there doesn't seem to be anything significantly different between the two algorithmically. The only real differences would be computational optimizations.

I think this change can be done in a way that remains backwards compatible, which would be my intent. So using SPAMS would remain an option, but I think it is wise to pursue something that is showing signs of being actively maintained and does not have problems with newer versions of its dependencies.

**Comment by jakirkham** [comment]
attn: @dudmanj

**Comment by jakirkham** [comment]
So, the `numpy` 1.10 problem can be fixed by patching `spams` as is done here ( https://github.com/nanshe-org/nanshe-build/pull/11 ). A description of the problem and the patch that solves it has been emailed to Julien Mairal. However, there has been no response from him or anyone else developing `spams` on this issue at this time.

**Comment by jakirkham** [comment]
Currently, SPAMS will also block Python 3.x support. It isn't even a simple manner of cleaning up the Python code. There is a substantial amount of the C-API that will need to be changed. This seems like an unreasonable amount of work to pursue. So, in order to support the newer Python 3.x platform, am going to revisit removing or at least making this dependency optional.

**Comment by jakirkham** [comment]
After doing a closer comparison it was found that on smaller datasets scikit-learn was a bit slower and on larger datasets it was a bit faster. However, these were in no way comprehensive in their comparisons and the differences were not so painful that they could be accepted. The difference is likely due to how much is done on the C/C++ side vs Python. Also, there is probably some releasing and acquiring the GIL that hurts scikit-learn until the data size is large. In short, there is no particular pressing reason to stay with SPAMS considering it is not currently being supported and restricts us in several ways.

**Comment by jakirkham** [comment]
We support using SPAMS and scikit-learn at this point and ship with it. There are a few cases that scikit-learn has issues that SPAMS does not, which will require closer inspection.

**Comment by jakirkham** [comment]
Both options are available thanks to PR ( https://github.com/nanshe-org/nanshe/pull/345 ).
